# secrets.REMOTE_HOST: The VPS IP address
# secrets.REMOTE_USER: The VPS user name
# secrets.REMOTE_PORT: The VPS ssh connection port (default 22)
# secrets.REMOTE_WORK_DIR: The VPS working directory for deploying
# secrets.SERVER_SSH_KEY: Public SSH for VPS authentication
# vars.APP_URL: Deployed app url

name: devjose-portfolio.com.br deployment

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{vars.APP_URL}}
    steps:
      - name: VPS Build
        uses: appleboy/ssh-action@v1.0.3
        with:
          key: ${{secrets.SERVER_SSH_KEY}}
          host: ${{secrets.REMOTE_HOST}}
          username: ${{secrets.REMOTE_USER}}
          port: ${{secrets.REMOTE_PORT}}
          script: |
            echo "Setting up environment"
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
            git config --global --add safe.directory ${{secrets.REMOTE_WORK_DIR}}
            cd ${{secrets.REMOTE_WORK_DIR}}
            git fetch origin
            git reset --hard origin/master
            git checkout master
            git pull
            npm run docker:deploy
          debug: true